# Site Build Settings

# Base url, set to '' when previewing locally using jekyll serve --baseurl ''
baseurl:             /alejandrogonzalez.net

# jekyll-paginate configuration
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag, jekyll-datapage-generator]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title:		           "Alejandro Gonzalez"
description:	       "Fotografía"
author:              "Alejandro Gonzalez"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
#feed:
#  path: rss-feed.xml

# Page generator
page_gen-dirs: true
page_gen:
  - data: 'pictures'
    template: 'gallery'
    name: 'page'
    dir: ''
