menu:
- {name: 'About',              url: 'about'}

social:
- {icon: 'facebook', link:   'https://www.facebook.com/profile.php?id=100042368234791'}
- {icon: 'instagram', link:  'https://instagram.com/alejophoto1945'}
- {icon: 'envelope', link:   'mailto:alegon1945@gmail.com'}
